/**************************************************************************/
/*                                                                        */
/*                                 OCaml                                  */
/*                                                                        */
/*                         Tim McGilchrist, Tarides                       */
/*                                                                        */
/*   Copyright 2025 Tarides                                               */
/*                                                                        */
/*   All rights reserved.  This file is distributed under the terms of    */
/*   the GNU Lesser General Public License version 2.1, with the          */
/*   special exception on linking described in the file LICENSE.          */
/*                                                                        */
/**************************************************************************/

/* USDT (Userland Statically Defined Tracing) probe definitions for OCaml
 *
 * This file defines USDT probes for tracing OCaml runtime events using
 * DTrace, SystemTap, bpftrace, and other compatible tracing tools.
 *
 * Probes are compiled as NOP instructions when not actively traced,
 * providing minimal overhead (~1-2ns per probe).
 *
 * These probes complement the existing runtime_events system:
 * - Runtime events: Ring buffer-based, OCaml-specific tooling
 * - USDT probes: System-wide tracing, standard Unix tools
 *
 * Platform support:
 *   - Linux: Uses SystemTap SDT (<sys/sdt.h> with DTRACE_PROBE macros)
 *   - macOS: Uses DTrace (ocaml_probes.h generated from ocaml_probes.d)
 *   - FreeBSD: Uses DTrace (ocaml_probes.h generated from ocaml_probes.d)
 *
 * To enable USDT probes:
 *   ./configure --enable-usdt
 */

#ifndef CAML_USDT_PROBES_H
#define CAML_USDT_PROBES_H

#ifdef CAML_WITH_USDT

#if defined(__APPLE__) || defined(__FreeBSD__)
/*
 * macOS and FreeBSD use DTrace with generated headers.
 * The ocaml_probes.h header is generated by dtrace -h from ocaml_probes.d
 * and provides the probe macros (e.g., OCAML_GC_MINOR_BEGIN()).
 *
 * The generated header uses $ in identifiers (e.g.,
 * __dtrace_probe$ocaml$gc__minor__begin$v1), which is standard DTrace
 * convention on macOS.
 */
#include "ocaml_probes.h"
#else
/*
 * Linux uses SystemTap SDT which provides DTRACE_PROBE macros directly.
 * Check if the header is available.
 */
#if __has_include(<sys/sdt.h>)
#include <sys/sdt.h>
#else
/* sys/sdt.h not found - disable USDT even though CAML_WITH_USDT was set */
#undef CAML_WITH_USDT
#warning "CAML_WITH_USDT defined but sys/sdt.h not found, disabling USDT"
#endif
#endif

#endif /* CAML_WITH_USDT */

/* Provider name for all OCaml runtime probes */
#define OCAML_PROVIDER ocaml

/*
 * Probe definitions
 *
 * On Linux (SystemTap SDT): Probes use DTRACE_PROBE macros
 * On macOS/FreeBSD: Probes use generated macros (e.g., OCAML_GC_MINOR_BEGIN())
 *
 * We provide a unified interface (OCAML_USDT_*) that works on all platforms.
 */

#ifdef CAML_WITH_USDT

/*
 * Platform-specific probe invocation
 *
 * On macOS/FreeBSD, dtrace -h generates macros like OCAML_GC_MINOR_BEGIN().
 * On Linux with SystemTap, we use DTRACE_PROBE() directly.
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
/* Use generated DTrace macros */
#define OCAML_PROBE_ENABLED(name) name##_ENABLED()
#else
/* Linux SystemTap - use DTRACE_PROBE directly */
#define OCAML_PROBE_ENABLED(name) 1
#endif

/* ========================================================================
 * GC Phase Probes
 * ======================================================================== */

/* Minor GC - fired at start/end of minor collection
 * Maps to: CAML_EV_BEGIN(EV_MINOR) / CAML_EV_END(EV_MINOR)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_MINOR_BEGIN(domain_id) \
    OCAML_GC_MINOR_BEGIN(domain_id)
#else
#define OCAML_USDT_GC_MINOR_BEGIN(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, gc__minor__begin, domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_MINOR_END(domain_id, promoted_words, allocated_words) \
    OCAML_GC_MINOR_END(domain_id, promoted_words, allocated_words)
#else
#define OCAML_USDT_GC_MINOR_END(domain_id, promoted_words, allocated_words) \
    DTRACE_PROBE3(OCAML_PROVIDER, gc__minor__end, \
                  domain_id, promoted_words, allocated_words)
#endif

/* Major GC - fired at start/end of major collection phases
 * Maps to: CAML_EV_BEGIN(EV_MAJOR) / CAML_EV_END(EV_MAJOR)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_MAJOR_BEGIN(domain_id) \
    OCAML_GC_MAJOR_BEGIN(domain_id)
#else
#define OCAML_USDT_GC_MAJOR_BEGIN(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, gc__major__begin, domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_MAJOR_END(domain_id) \
    OCAML_GC_MAJOR_END(domain_id)
#else
#define OCAML_USDT_GC_MAJOR_END(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, gc__major__end, domain_id)
#endif

/* Major GC Slice - fired for incremental major GC slices
 * Maps to: CAML_EV_BEGIN(EV_MAJOR_SLICE) / CAML_EV_END(EV_MAJOR_SLICE)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_MAJOR_SLICE_BEGIN(domain_id) \
    OCAML_GC_MAJOR_SLICE_BEGIN(domain_id)
#else
#define OCAML_USDT_GC_MAJOR_SLICE_BEGIN(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, gc__major__slice__begin, domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_MAJOR_SLICE_END(domain_id, marked_words) \
    OCAML_GC_MAJOR_SLICE_END(domain_id, marked_words)
#else
#define OCAML_USDT_GC_MAJOR_SLICE_END(domain_id, marked_words) \
    DTRACE_PROBE2(OCAML_PROVIDER, gc__major__slice__end, domain_id, marked_words)
#endif

/* Heap Compaction - fired for rare but expensive compaction events
 * Maps to: CAML_EV_BEGIN(EV_COMPACT) / CAML_EV_END(EV_COMPACT)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_COMPACT_BEGIN(domain_id) \
    OCAML_GC_COMPACT_BEGIN(domain_id)
#else
#define OCAML_USDT_GC_COMPACT_BEGIN(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, gc__compact__begin, domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_GC_COMPACT_END(domain_id) \
    OCAML_GC_COMPACT_END(domain_id)
#else
#define OCAML_USDT_GC_COMPACT_END(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, gc__compact__end, domain_id)
#endif

/* ========================================================================
 * GC Sub-Phase Probes (ev_runtime_phase)
 * ========================================================================
 * Helper macros to reduce boilerplate for begin/end phase probes that
 * take a single domain_id argument.
 *
 * UPPER: uppercase token for macOS/FreeBSD generated macro
 * lower: double-underscore-separated token for Linux SDT probe name
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_PHASE1_BEGIN(UPPER, lower, domain_id) \
    OCAML_##UPPER##_BEGIN(domain_id)
#define OCAML_USDT_PHASE1_END(UPPER, lower, domain_id) \
    OCAML_##UPPER##_END(domain_id)
#else
#define OCAML_USDT_PHASE1_BEGIN(UPPER, lower, domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, lower##__begin, domain_id)
#define OCAML_USDT_PHASE1_END(UPPER, lower, domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, lower##__end, domain_id)
#endif

/* --- Minor GC sub-phases --- */

#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_LOCAL_ROOTS, \
        gc__minor__local__roots, did)
#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_LOCAL_ROOTS, \
        gc__minor__local__roots, did)

#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_PROMOTE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_LOCAL_ROOTS_PROMOTE, \
        gc__minor__local__roots__promote, did)
#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_PROMOTE_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_LOCAL_ROOTS_PROMOTE, \
        gc__minor__local__roots__promote, did)

#define OCAML_USDT_GC_MINOR_MEMPROF_ROOTS_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_MEMPROF_ROOTS, \
        gc__minor__memprof__roots, did)
#define OCAML_USDT_GC_MINOR_MEMPROF_ROOTS_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_MEMPROF_ROOTS, \
        gc__minor__memprof__roots, did)

#define OCAML_USDT_GC_MINOR_MEMPROF_CLEAN_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_MEMPROF_CLEAN, \
        gc__minor__memprof__clean, did)
#define OCAML_USDT_GC_MINOR_MEMPROF_CLEAN_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_MEMPROF_CLEAN, \
        gc__minor__memprof__clean, did)

#define OCAML_USDT_GC_MINOR_EPHE_CLEAN_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_EPHE_CLEAN, \
        gc__minor__ephe__clean, did)
#define OCAML_USDT_GC_MINOR_EPHE_CLEAN_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_EPHE_CLEAN, \
        gc__minor__ephe__clean, did)

#define OCAML_USDT_GC_MINOR_FINALIZED_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_FINALIZED, \
        gc__minor__finalized, did)
#define OCAML_USDT_GC_MINOR_FINALIZED_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_FINALIZED, \
        gc__minor__finalized, did)

#define OCAML_USDT_GC_MINOR_FINALIZERS_OLDIFY_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_FINALIZERS_OLDIFY, \
        gc__minor__finalizers__oldify, did)
#define OCAML_USDT_GC_MINOR_FINALIZERS_OLDIFY_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_FINALIZERS_OLDIFY, \
        gc__minor__finalizers__oldify, did)

#define OCAML_USDT_GC_MINOR_FINALIZERS_ADMIN_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_FINALIZERS_ADMIN, \
        gc__minor__finalizers__admin, did)
#define OCAML_USDT_GC_MINOR_FINALIZERS_ADMIN_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_FINALIZERS_ADMIN, \
        gc__minor__finalizers__admin, did)

#define OCAML_USDT_GC_MINOR_CLEAR_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_CLEAR, \
        gc__minor__clear, did)
#define OCAML_USDT_GC_MINOR_CLEAR_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_CLEAR, \
        gc__minor__clear, did)

#define OCAML_USDT_GC_MINOR_GLOBAL_ROOTS_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_GLOBAL_ROOTS, \
        gc__minor__global__roots, did)
#define OCAML_USDT_GC_MINOR_GLOBAL_ROOTS_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_GLOBAL_ROOTS, \
        gc__minor__global__roots, did)

#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_REMEMBERED_SET, \
        gc__minor__remembered__set, did)
#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_REMEMBERED_SET, \
        gc__minor__remembered__set, did)

#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_PROMOTE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_REMEMBERED_SET_PROMOTE, \
        gc__minor__remembered__set__promote, did)
#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_PROMOTE_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_REMEMBERED_SET_PROMOTE, \
        gc__minor__remembered__set__promote, did)

#define OCAML_USDT_GC_MINOR_LEAVE_BARRIER_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MINOR_LEAVE_BARRIER, \
        gc__minor__leave__barrier, did)
#define OCAML_USDT_GC_MINOR_LEAVE_BARRIER_END(did) \
    OCAML_USDT_PHASE1_END(GC_MINOR_LEAVE_BARRIER, \
        gc__minor__leave__barrier, did)

#define OCAML_USDT_GC_EMPTY_MINOR_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_EMPTY_MINOR, \
        gc__empty__minor, did)
#define OCAML_USDT_GC_EMPTY_MINOR_END(did) \
    OCAML_USDT_PHASE1_END(GC_EMPTY_MINOR, \
        gc__empty__minor, did)

/* --- Major GC sub-phases --- */

#define OCAML_USDT_GC_MAJOR_SWEEP_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_SWEEP, \
        gc__major__sweep, did)
#define OCAML_USDT_GC_MAJOR_SWEEP_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_SWEEP, \
        gc__major__sweep, did)

#define OCAML_USDT_GC_MAJOR_MARK_ROOTS_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_MARK_ROOTS, \
        gc__major__mark__roots, did)
#define OCAML_USDT_GC_MAJOR_MARK_ROOTS_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_MARK_ROOTS, \
        gc__major__mark__roots, did)

#define OCAML_USDT_GC_MAJOR_MARK_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_MARK, \
        gc__major__mark, did)
#define OCAML_USDT_GC_MAJOR_MARK_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_MARK, \
        gc__major__mark, did)

#define OCAML_USDT_GC_MAJOR_MARK_OPPORTUNISTIC_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_MARK_OPPORTUNISTIC, \
        gc__major__mark__opportunistic, did)
#define OCAML_USDT_GC_MAJOR_MARK_OPPORTUNISTIC_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_MARK_OPPORTUNISTIC, \
        gc__major__mark__opportunistic, did)

#define OCAML_USDT_GC_MAJOR_MEMPROF_ROOTS_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_MEMPROF_ROOTS, \
        gc__major__memprof__roots, did)
#define OCAML_USDT_GC_MAJOR_MEMPROF_ROOTS_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_MEMPROF_ROOTS, \
        gc__major__memprof__roots, did)

#define OCAML_USDT_GC_MAJOR_MEMPROF_CLEAN_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_MEMPROF_CLEAN, \
        gc__major__memprof__clean, did)
#define OCAML_USDT_GC_MAJOR_MEMPROF_CLEAN_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_MEMPROF_CLEAN, \
        gc__major__memprof__clean, did)

#define OCAML_USDT_GC_MAJOR_EPHE_MARK_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_EPHE_MARK, \
        gc__major__ephe__mark, did)
#define OCAML_USDT_GC_MAJOR_EPHE_MARK_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_EPHE_MARK, \
        gc__major__ephe__mark, did)

#define OCAML_USDT_GC_MAJOR_EPHE_SWEEP_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_EPHE_SWEEP, \
        gc__major__ephe__sweep, did)
#define OCAML_USDT_GC_MAJOR_EPHE_SWEEP_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_EPHE_SWEEP, \
        gc__major__ephe__sweep, did)

#define OCAML_USDT_GC_MAJOR_FINISH_MARKING_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_FINISH_MARKING, \
        gc__major__finish__marking, did)
#define OCAML_USDT_GC_MAJOR_FINISH_MARKING_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_FINISH_MARKING, \
        gc__major__finish__marking, did)

#define OCAML_USDT_GC_MAJOR_FINISH_SWEEPING_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_FINISH_SWEEPING, \
        gc__major__finish__sweeping, did)
#define OCAML_USDT_GC_MAJOR_FINISH_SWEEPING_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_FINISH_SWEEPING, \
        gc__major__finish__sweeping, did)

#define OCAML_USDT_GC_MAJOR_FINISH_CYCLE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_FINISH_CYCLE, \
        gc__major__finish__cycle, did)
#define OCAML_USDT_GC_MAJOR_FINISH_CYCLE_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_FINISH_CYCLE, \
        gc__major__finish__cycle, did)

#define OCAML_USDT_GC_MAJOR_GC_CYCLE_DOMAINS_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_GC_CYCLE_DOMAINS, \
        gc__major__gc__cycle__domains, did)
#define OCAML_USDT_GC_MAJOR_GC_CYCLE_DOMAINS_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_GC_CYCLE_DOMAINS, \
        gc__major__gc__cycle__domains, did)

#define OCAML_USDT_GC_MAJOR_GC_PHASE_CHANGE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_GC_PHASE_CHANGE, \
        gc__major__gc__phase__change, did)
#define OCAML_USDT_GC_MAJOR_GC_PHASE_CHANGE_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_GC_PHASE_CHANGE, \
        gc__major__gc__phase__change, did)

#define OCAML_USDT_GC_MAJOR_GC_STW_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_MAJOR_GC_STW, \
        gc__major__gc__stw, did)
#define OCAML_USDT_GC_MAJOR_GC_STW_END(did) \
    OCAML_USDT_PHASE1_END(GC_MAJOR_GC_STW, \
        gc__major__gc__stw, did)

/* --- Compaction sub-phases --- */

#define OCAML_USDT_GC_COMPACT_EVACUATE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_COMPACT_EVACUATE, \
        gc__compact__evacuate, did)
#define OCAML_USDT_GC_COMPACT_EVACUATE_END(did) \
    OCAML_USDT_PHASE1_END(GC_COMPACT_EVACUATE, \
        gc__compact__evacuate, did)

#define OCAML_USDT_GC_COMPACT_FORWARD_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_COMPACT_FORWARD, \
        gc__compact__forward, did)
#define OCAML_USDT_GC_COMPACT_FORWARD_END(did) \
    OCAML_USDT_PHASE1_END(GC_COMPACT_FORWARD, \
        gc__compact__forward, did)

#define OCAML_USDT_GC_COMPACT_RELEASE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(GC_COMPACT_RELEASE, \
        gc__compact__release, did)
#define OCAML_USDT_GC_COMPACT_RELEASE_END(did) \
    OCAML_USDT_PHASE1_END(GC_COMPACT_RELEASE, \
        gc__compact__release, did)

/* --- Explicit GC calls --- */

#define OCAML_USDT_EXPLICIT_GC_SET_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_SET, \
        explicit__gc__set, did)
#define OCAML_USDT_EXPLICIT_GC_SET_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_SET, \
        explicit__gc__set, did)

#define OCAML_USDT_EXPLICIT_GC_STAT_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_STAT, \
        explicit__gc__stat, did)
#define OCAML_USDT_EXPLICIT_GC_STAT_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_STAT, \
        explicit__gc__stat, did)

#define OCAML_USDT_EXPLICIT_GC_MINOR_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_MINOR, \
        explicit__gc__minor, did)
#define OCAML_USDT_EXPLICIT_GC_MINOR_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_MINOR, \
        explicit__gc__minor, did)

#define OCAML_USDT_EXPLICIT_GC_MAJOR_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_MAJOR, \
        explicit__gc__major, did)
#define OCAML_USDT_EXPLICIT_GC_MAJOR_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_MAJOR, \
        explicit__gc__major, did)

#define OCAML_USDT_EXPLICIT_GC_FULL_MAJOR_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_FULL_MAJOR, \
        explicit__gc__full__major, did)
#define OCAML_USDT_EXPLICIT_GC_FULL_MAJOR_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_FULL_MAJOR, \
        explicit__gc__full__major, did)

#define OCAML_USDT_EXPLICIT_GC_COMPACT_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_COMPACT, \
        explicit__gc__compact, did)
#define OCAML_USDT_EXPLICIT_GC_COMPACT_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_COMPACT, \
        explicit__gc__compact, did)

#define OCAML_USDT_EXPLICIT_GC_MAJOR_SLICE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(EXPLICIT_GC_MAJOR_SLICE, \
        explicit__gc__major__slice, did)
#define OCAML_USDT_EXPLICIT_GC_MAJOR_SLICE_END(did) \
    OCAML_USDT_PHASE1_END(EXPLICIT_GC_MAJOR_SLICE, \
        explicit__gc__major__slice, did)

/* --- Finaliser phases --- */

#define OCAML_USDT_FINALISE_UPDATE_FIRST_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(FINALISE_UPDATE_FIRST, \
        finalise__update__first, did)
#define OCAML_USDT_FINALISE_UPDATE_FIRST_END(did) \
    OCAML_USDT_PHASE1_END(FINALISE_UPDATE_FIRST, \
        finalise__update__first, did)

#define OCAML_USDT_FINALISE_UPDATE_LAST_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(FINALISE_UPDATE_LAST, \
        finalise__update__last, did)
#define OCAML_USDT_FINALISE_UPDATE_LAST_END(did) \
    OCAML_USDT_PHASE1_END(FINALISE_UPDATE_LAST, \
        finalise__update__last, did)

/* --- Domain runtime phases --- */

#define OCAML_USDT_DOMAIN_CONDITION_WAIT_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(DOMAIN_CONDITION_WAIT, \
        domain__condition__wait, did)
#define OCAML_USDT_DOMAIN_CONDITION_WAIT_END(did) \
    OCAML_USDT_PHASE1_END(DOMAIN_CONDITION_WAIT, \
        domain__condition__wait, did)

#define OCAML_USDT_DOMAIN_RESIZE_HEAP_RESERVATION_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(DOMAIN_RESIZE_HEAP_RESERVATION, \
        domain__resize__heap__reservation, did)
#define OCAML_USDT_DOMAIN_RESIZE_HEAP_RESERVATION_END(did) \
    OCAML_USDT_PHASE1_END(DOMAIN_RESIZE_HEAP_RESERVATION, \
        domain__resize__heap__reservation, did)

/* --- STW phases --- */

#define OCAML_USDT_STW_API_BARRIER_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(STW_API_BARRIER, \
        stw__api__barrier, did)
#define OCAML_USDT_STW_API_BARRIER_END(did) \
    OCAML_USDT_PHASE1_END(STW_API_BARRIER, \
        stw__api__barrier, did)

#define OCAML_USDT_STW_HANDLER_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(STW_HANDLER, \
        stw__handler, did)
#define OCAML_USDT_STW_HANDLER_END(did) \
    OCAML_USDT_PHASE1_END(STW_HANDLER, \
        stw__handler, did)

#define OCAML_USDT_STW_LEADER_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(STW_LEADER, \
        stw__leader, did)
#define OCAML_USDT_STW_LEADER_END(did) \
    OCAML_USDT_PHASE1_END(STW_LEADER, \
        stw__leader, did)

/* --- Interrupt --- */

#define OCAML_USDT_INTERRUPT_REMOTE_BEGIN(did) \
    OCAML_USDT_PHASE1_BEGIN(INTERRUPT_REMOTE, \
        interrupt__remote, did)
#define OCAML_USDT_INTERRUPT_REMOTE_END(did) \
    OCAML_USDT_PHASE1_END(INTERRUPT_REMOTE, \
        interrupt__remote, did)

/* ========================================================================
 * Allocation Probes
 * ======================================================================== */

/* Minor heap allocation
 * Maps to: CAML_EV_COUNTER(EV_C_MINOR_ALLOCATED_WORDS, ...)
 * Note: High frequency - use with filtering in tracer
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_ALLOC_MINOR(domain_id, size_words) \
    OCAML_ALLOC_MINOR(domain_id, size_words)
#else
#define OCAML_USDT_ALLOC_MINOR(domain_id, size_words) \
    DTRACE_PROBE2(OCAML_PROVIDER, alloc__minor, domain_id, size_words)
#endif

/* Major heap allocation
 * Maps to: CAML_EV_COUNTER(EV_C_MAJOR_ALLOCATED_WORDS, ...)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_ALLOC_MAJOR(domain_id, size_words) \
    OCAML_ALLOC_MAJOR(domain_id, size_words)
#else
#define OCAML_USDT_ALLOC_MAJOR(domain_id, size_words) \
    DTRACE_PROBE2(OCAML_PROVIDER, alloc__major, domain_id, size_words)
#endif

/* ========================================================================
 * Domain/Thread Lifecycle Probes
 * ======================================================================== */

/* Domain spawn
 * Maps to: CAML_EV_LIFECYCLE(EV_DOMAIN_SPAWN, ...)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_DOMAIN_SPAWN(domain_id) \
    OCAML_DOMAIN_SPAWN(domain_id)
#else
#define OCAML_USDT_DOMAIN_SPAWN(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, domain__spawn, domain_id)
#endif

/* Domain termination
 * Maps to: CAML_EV_LIFECYCLE(EV_DOMAIN_TERMINATE, ...)
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_DOMAIN_TERMINATE(domain_id) \
    OCAML_DOMAIN_TERMINATE(domain_id)
#else
#define OCAML_USDT_DOMAIN_TERMINATE(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, domain__terminate, domain_id)
#endif

/* ========================================================================
 * Runtime Lifecycle Probes
 * ======================================================================== */

/* Runtime initialization complete
 * Maps to: EV_RING_START lifecycle event
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_RUNTIME_BEGIN() \
    OCAML_RUNTIME_BEGIN()
#else
#define OCAML_USDT_RUNTIME_BEGIN() \
    DTRACE_PROBE(OCAML_PROVIDER, runtime__begin)
#endif

/* Runtime shutdown beginning
 * Maps to: EV_RING_STOP lifecycle event
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_RUNTIME_END() \
    OCAML_RUNTIME_END()
#else
#define OCAML_USDT_RUNTIME_END() \
    DTRACE_PROBE(OCAML_PROVIDER, runtime__end)
#endif

/* ========================================================================
 * STW (Stop-The-World) Event Probes
 * ======================================================================== */

/* STW event beginning - all domains pausing for coordination
 * Maps to: CAML_EV_BEGIN(EV_STW_LEADER) / EV_STW_HANDLER / EV_MAJOR_GC_STW
 * reason: 0=GC, 1=API_BARRIER, 2=other
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_STW_BEGIN(domain_id, reason) \
    OCAML_STW_BEGIN(domain_id, reason)
#else
#define OCAML_USDT_STW_BEGIN(domain_id, reason) \
    DTRACE_PROBE2(OCAML_PROVIDER, stw__begin, domain_id, reason)
#endif

/* STW event complete
 * duration_ns: time spent in STW in nanoseconds
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_STW_END(domain_id, duration_ns) \
    OCAML_STW_END(domain_id, duration_ns)
#else
#define OCAML_USDT_STW_END(domain_id, duration_ns) \
    DTRACE_PROBE2(OCAML_PROVIDER, stw__end, domain_id, duration_ns)
#endif

/* STW interrupt sent from leader to target domain
 * For debugging STW synchronization delays
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_STW_INTERRUPT_SENT(leader_id, target_domain_id) \
    OCAML_STW_INTERRUPT_SENT(leader_id, target_domain_id)
#else
#define OCAML_USDT_STW_INTERRUPT_SENT(leader_id, target_domain_id) \
    DTRACE_PROBE2(OCAML_PROVIDER, stw__interrupt__sent, \
                  leader_id, target_domain_id)
#endif

/* STW handler entry by domain
 * Fires at the very start of stw_handler, before any work
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_STW_HANDLER_ENTER(domain_id) \
    OCAML_STW_HANDLER_ENTER(domain_id)
#else
#define OCAML_USDT_STW_HANDLER_ENTER(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, stw__handler__enter, domain_id)
#endif

/* STW barrier entry by domain
 * barrier_id: 0=API_BARRIER, 1=domains_still_running, etc.
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_STW_BARRIER_ENTER(domain_id, barrier_id) \
    OCAML_STW_BARRIER_ENTER(domain_id, barrier_id)
#else
#define OCAML_USDT_STW_BARRIER_ENTER(domain_id, barrier_id) \
    DTRACE_PROBE2(OCAML_PROVIDER, stw__barrier__enter, \
                  domain_id, barrier_id)
#endif

/* ========================================================================
 * Memory Heap Statistics Probes
 * ======================================================================== */

/* Heap statistics snapshot
 * Aggregates: EV_C_MAJOR_HEAP_WORDS, EV_C_MINOR_ALLOCATED_WORDS, etc.
 * Fired periodically or after major GC events
 */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_HEAP_STATS(domain_id, minor_words, major_words, live_words) \
    OCAML_HEAP_STATS(domain_id, minor_words, major_words, live_words)
#else
#define OCAML_USDT_HEAP_STATS(domain_id, minor_words, major_words, live_words) \
    DTRACE_PROBE4(OCAML_PROVIDER, heap__stats, \
                  domain_id, minor_words, major_words, live_words)
#endif

/* ========================================================================
 * Runtime Event Counter Probes
 * ========================================================================
 * These probes correspond to CAML_EV_COUNTER calls in the runtime.
 * They provide detailed metrics about GC behavior, heap statistics,
 * and allocation patterns.
 */

/* Minor GC counters */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MINOR_PROMOTED(domain_id, bytes) \
    OCAML_COUNTER_MINOR_PROMOTED(domain_id, bytes)
#else
#define OCAML_USDT_COUNTER_MINOR_PROMOTED(domain_id, bytes) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__minor__promoted, \
                  domain_id, bytes)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MINOR_PROMOTED_WORDS(domain_id, words) \
    OCAML_COUNTER_MINOR_PROMOTED_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MINOR_PROMOTED_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__minor__promoted__words, \
                  domain_id, words)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MINOR_ALLOCATED(domain_id, bytes) \
    OCAML_COUNTER_MINOR_ALLOCATED(domain_id, bytes)
#else
#define OCAML_USDT_COUNTER_MINOR_ALLOCATED(domain_id, bytes) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__minor__allocated, \
                  domain_id, bytes)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MINOR_ALLOCATED_WORDS(domain_id, words) \
    OCAML_COUNTER_MINOR_ALLOCATED_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MINOR_ALLOCATED_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__minor__allocated__words, \
                  domain_id, words)
#endif

/* Force minor GC counters - track why minor GC was triggered */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_FORCE_MINOR_ALLOC_SMALL(domain_id) \
    OCAML_COUNTER_FORCE_MINOR_ALLOC_SMALL(domain_id)
#else
#define OCAML_USDT_COUNTER_FORCE_MINOR_ALLOC_SMALL(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, counter__force__minor__alloc__small, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_FORCE_MINOR_MAKE_VECT(domain_id) \
    OCAML_COUNTER_FORCE_MINOR_MAKE_VECT(domain_id)
#else
#define OCAML_USDT_COUNTER_FORCE_MINOR_MAKE_VECT(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, counter__force__minor__make__vect, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_FORCE_MINOR_SET_MINOR_HEAP_SIZE(domain_id) \
    OCAML_COUNTER_FORCE_MINOR_SET_MINOR_HEAP_SIZE(domain_id)
#else
#define OCAML_USDT_COUNTER_FORCE_MINOR_SET_MINOR_HEAP_SIZE(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, \
                  counter__force__minor__set__minor__heap__size, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_FORCE_MINOR_MEMPROF(domain_id) \
    OCAML_COUNTER_FORCE_MINOR_MEMPROF(domain_id)
#else
#define OCAML_USDT_COUNTER_FORCE_MINOR_MEMPROF(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, counter__force__minor__memprof, \
                  domain_id)
#endif

/* Major GC heap counters */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_WORDS(domain_id, words) \
    OCAML_COUNTER_MAJOR_HEAP_POOL_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__heap__pool__words, \
                  domain_id, words)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_LIVE_WORDS(domain_id, words) \
    OCAML_COUNTER_MAJOR_HEAP_POOL_LIVE_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_LIVE_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, \
                  counter__major__heap__pool__live__words, \
                  domain_id, words)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_LARGE_WORDS(domain_id, words) \
    OCAML_COUNTER_MAJOR_HEAP_LARGE_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_LARGE_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__heap__large__words, \
                  domain_id, words)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_FRAG_WORDS(domain_id, words) \
    OCAML_COUNTER_MAJOR_HEAP_POOL_FRAG_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_FRAG_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, \
                  counter__major__heap__pool__frag__words, \
                  domain_id, words)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_LIVE_BLOCKS(domain_id, blocks) \
    OCAML_COUNTER_MAJOR_HEAP_POOL_LIVE_BLOCKS(domain_id, blocks)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_LIVE_BLOCKS(domain_id, blocks) \
    DTRACE_PROBE2(OCAML_PROVIDER, \
                  counter__major__heap__pool__live__blocks, \
                  domain_id, blocks)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_LARGE_BLOCKS(domain_id, blocks) \
    OCAML_COUNTER_MAJOR_HEAP_LARGE_BLOCKS(domain_id, blocks)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_LARGE_BLOCKS(domain_id, blocks) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__heap__large__blocks, \
                  domain_id, blocks)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_WORDS(domain_id, words) \
    OCAML_COUNTER_MAJOR_HEAP_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MAJOR_HEAP_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__heap__words, \
                  domain_id, words)
#endif

/* Major GC allocation and work counters */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_ALLOCATED_WORDS(domain_id, words) \
    OCAML_COUNTER_MAJOR_ALLOCATED_WORDS(domain_id, words)
#else
#define OCAML_USDT_COUNTER_MAJOR_ALLOCATED_WORDS(domain_id, words) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__allocated__words, \
                  domain_id, words)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_ALLOCATED_WORK(domain_id, work) \
    OCAML_COUNTER_MAJOR_ALLOCATED_WORK(domain_id, work)
#else
#define OCAML_USDT_COUNTER_MAJOR_ALLOCATED_WORK(domain_id, work) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__allocated__work, \
                  domain_id, work)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_DEPENDENT_WORK(domain_id, work) \
    OCAML_COUNTER_MAJOR_DEPENDENT_WORK(domain_id, work)
#else
#define OCAML_USDT_COUNTER_MAJOR_DEPENDENT_WORK(domain_id, work) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__dependent__work, \
                  domain_id, work)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_EXTRA_WORK(domain_id, work) \
    OCAML_COUNTER_MAJOR_EXTRA_WORK(domain_id, work)
#else
#define OCAML_USDT_COUNTER_MAJOR_EXTRA_WORK(domain_id, work) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__extra__work, \
                  domain_id, work)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_WORK_COUNTER(domain_id, counter) \
    OCAML_COUNTER_MAJOR_WORK_COUNTER(domain_id, counter)
#else
#define OCAML_USDT_COUNTER_MAJOR_WORK_COUNTER(domain_id, counter) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__work__counter, \
                  domain_id, counter)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_ALLOC_COUNTER(domain_id, counter) \
    OCAML_COUNTER_MAJOR_ALLOC_COUNTER(domain_id, counter)
#else
#define OCAML_USDT_COUNTER_MAJOR_ALLOC_COUNTER(domain_id, counter) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__alloc__counter, \
                  domain_id, counter)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_SLICE_TARGET(domain_id, target) \
    OCAML_COUNTER_MAJOR_SLICE_TARGET(domain_id, target)
#else
#define OCAML_USDT_COUNTER_MAJOR_SLICE_TARGET(domain_id, target) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__slice__target, \
                  domain_id, target)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_MAJOR_SLICE_BUDGET(domain_id, budget) \
    OCAML_COUNTER_MAJOR_SLICE_BUDGET(domain_id, budget)
#else
#define OCAML_USDT_COUNTER_MAJOR_SLICE_BUDGET(domain_id, budget) \
    DTRACE_PROBE2(OCAML_PROVIDER, counter__major__slice__budget, \
                  domain_id, budget)
#endif

/* Request counters - track allocation and reallocation requests */
#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_REQUEST_MAJOR_ALLOC_SHR(domain_id) \
    OCAML_COUNTER_REQUEST_MAJOR_ALLOC_SHR(domain_id)
#else
#define OCAML_USDT_COUNTER_REQUEST_MAJOR_ALLOC_SHR(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, counter__request__major__alloc__shr, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_REQUEST_MAJOR_ADJUST_GC_SPEED(domain_id) \
    OCAML_COUNTER_REQUEST_MAJOR_ADJUST_GC_SPEED(domain_id)
#else
#define OCAML_USDT_COUNTER_REQUEST_MAJOR_ADJUST_GC_SPEED(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, \
                  counter__request__major__adjust__gc__speed, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_REF_TABLE(domain_id) \
    OCAML_COUNTER_REQUEST_MINOR_REALLOC_REF_TABLE(domain_id)
#else
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_REF_TABLE(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, \
                  counter__request__minor__realloc__ref__table, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE(domain_id) \
    OCAML_COUNTER_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE(domain_id)
#else
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, \
                  counter__request__minor__realloc__ephe__ref__table, \
                  domain_id)
#endif

#if defined(__APPLE__) || defined(__FreeBSD__)
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_CUSTOM_TABLE(domain_id) \
    OCAML_COUNTER_REQUEST_MINOR_REALLOC_CUSTOM_TABLE(domain_id)
#else
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_CUSTOM_TABLE(domain_id) \
    DTRACE_PROBE1(OCAML_PROVIDER, \
                  counter__request__minor__realloc__custom__table, \
                  domain_id)
#endif

/* ========================================================================
 * Probe Enabled Checks
 * ========================================================================
 *
 * These allow avoiding expensive argument computation when probe is not
 * actively being traced. Use pattern:
 *   if (OCAML_USDT_GC_MINOR_BEGIN_ENABLED()) {
 *       expensive_calculation();
 *       OCAML_USDT_GC_MINOR_BEGIN(domain_id);
 *   }
 */

#define OCAML_USDT_GC_MINOR_BEGIN_ENABLED() \
    DTRACE_PROBE_ENABLED(OCAML_PROVIDER, gc__minor__begin)

#define OCAML_USDT_GC_MAJOR_BEGIN_ENABLED() \
    DTRACE_PROBE_ENABLED(OCAML_PROVIDER, gc__major__begin)

#define OCAML_USDT_ALLOC_MINOR_ENABLED() \
    DTRACE_PROBE_ENABLED(OCAML_PROVIDER, alloc__minor)

#define OCAML_USDT_HEAP_STATS_ENABLED() \
    DTRACE_PROBE_ENABLED(OCAML_PROVIDER, heap__stats)

#else /* !CAML_WITH_USDT */

/* ========================================================================
 * No-op definitions when USDT is not available
 * ======================================================================== */

#define OCAML_USDT_GC_MINOR_BEGIN(domain_id) do {} while(0)
#define OCAML_USDT_GC_MINOR_END(domain_id, promoted_words, allocated_words) do {} while(0)
#define OCAML_USDT_GC_MAJOR_BEGIN(domain_id) do {} while(0)
#define OCAML_USDT_GC_MAJOR_END(domain_id) do {} while(0)
#define OCAML_USDT_GC_MAJOR_SLICE_BEGIN(domain_id) do {} while(0)
#define OCAML_USDT_GC_MAJOR_SLICE_END(domain_id, marked_words) do {} while(0)
#define OCAML_USDT_GC_COMPACT_BEGIN(domain_id) do {} while(0)
#define OCAML_USDT_GC_COMPACT_END(domain_id) do {} while(0)

/* Sub-phase no-ops */
#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_PROMOTE_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_LOCAL_ROOTS_PROMOTE_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_MEMPROF_ROOTS_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_MEMPROF_ROOTS_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_MEMPROF_CLEAN_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_MEMPROF_CLEAN_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_EPHE_CLEAN_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_EPHE_CLEAN_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_FINALIZED_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_FINALIZED_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_FINALIZERS_OLDIFY_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_FINALIZERS_OLDIFY_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_FINALIZERS_ADMIN_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_FINALIZERS_ADMIN_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_CLEAR_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_CLEAR_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_GLOBAL_ROOTS_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_GLOBAL_ROOTS_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_PROMOTE_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_REMEMBERED_SET_PROMOTE_END(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_LEAVE_BARRIER_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MINOR_LEAVE_BARRIER_END(did) do {} while(0)
#define OCAML_USDT_GC_EMPTY_MINOR_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_EMPTY_MINOR_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_SWEEP_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_SWEEP_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MARK_ROOTS_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MARK_ROOTS_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MARK_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MARK_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MARK_OPPORTUNISTIC_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MARK_OPPORTUNISTIC_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MEMPROF_ROOTS_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MEMPROF_ROOTS_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MEMPROF_CLEAN_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_MEMPROF_CLEAN_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_EPHE_MARK_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_EPHE_MARK_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_EPHE_SWEEP_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_EPHE_SWEEP_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_FINISH_MARKING_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_FINISH_MARKING_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_FINISH_SWEEPING_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_FINISH_SWEEPING_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_FINISH_CYCLE_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_FINISH_CYCLE_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_GC_CYCLE_DOMAINS_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_GC_CYCLE_DOMAINS_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_GC_PHASE_CHANGE_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_GC_PHASE_CHANGE_END(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_GC_STW_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_MAJOR_GC_STW_END(did) do {} while(0)
#define OCAML_USDT_GC_COMPACT_EVACUATE_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_COMPACT_EVACUATE_END(did) do {} while(0)
#define OCAML_USDT_GC_COMPACT_FORWARD_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_COMPACT_FORWARD_END(did) do {} while(0)
#define OCAML_USDT_GC_COMPACT_RELEASE_BEGIN(did) do {} while(0)
#define OCAML_USDT_GC_COMPACT_RELEASE_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_SET_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_SET_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_STAT_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_STAT_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_MINOR_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_MINOR_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_MAJOR_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_MAJOR_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_FULL_MAJOR_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_FULL_MAJOR_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_COMPACT_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_COMPACT_END(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_MAJOR_SLICE_BEGIN(did) do {} while(0)
#define OCAML_USDT_EXPLICIT_GC_MAJOR_SLICE_END(did) do {} while(0)
#define OCAML_USDT_FINALISE_UPDATE_FIRST_BEGIN(did) do {} while(0)
#define OCAML_USDT_FINALISE_UPDATE_FIRST_END(did) do {} while(0)
#define OCAML_USDT_FINALISE_UPDATE_LAST_BEGIN(did) do {} while(0)
#define OCAML_USDT_FINALISE_UPDATE_LAST_END(did) do {} while(0)
#define OCAML_USDT_DOMAIN_CONDITION_WAIT_BEGIN(did) do {} while(0)
#define OCAML_USDT_DOMAIN_CONDITION_WAIT_END(did) do {} while(0)
#define OCAML_USDT_DOMAIN_RESIZE_HEAP_RESERVATION_BEGIN(did) do {} while(0)
#define OCAML_USDT_DOMAIN_RESIZE_HEAP_RESERVATION_END(did) do {} while(0)
#define OCAML_USDT_STW_API_BARRIER_BEGIN(did) do {} while(0)
#define OCAML_USDT_STW_API_BARRIER_END(did) do {} while(0)
#define OCAML_USDT_STW_HANDLER_BEGIN(did) do {} while(0)
#define OCAML_USDT_STW_HANDLER_END(did) do {} while(0)
#define OCAML_USDT_STW_LEADER_BEGIN(did) do {} while(0)
#define OCAML_USDT_STW_LEADER_END(did) do {} while(0)
#define OCAML_USDT_INTERRUPT_REMOTE_BEGIN(did) do {} while(0)
#define OCAML_USDT_INTERRUPT_REMOTE_END(did) do {} while(0)

#define OCAML_USDT_ALLOC_MINOR(domain_id, size_words) do {} while(0)
#define OCAML_USDT_ALLOC_MAJOR(domain_id, size_words) do {} while(0)
#define OCAML_USDT_DOMAIN_SPAWN(domain_id) do {} while(0)
#define OCAML_USDT_DOMAIN_TERMINATE(domain_id) do {} while(0)
#define OCAML_USDT_RUNTIME_BEGIN() do {} while(0)
#define OCAML_USDT_RUNTIME_END() do {} while(0)
#define OCAML_USDT_STW_BEGIN(domain_id, reason) do {} while(0)
#define OCAML_USDT_STW_END(domain_id, duration_ns) do {} while(0)
#define OCAML_USDT_STW_INTERRUPT_SENT(leader_id, target_domain_id) do {} while(0)
#define OCAML_USDT_STW_HANDLER_ENTER(domain_id) do {} while(0)
#define OCAML_USDT_STW_BARRIER_ENTER(domain_id, barrier_id) do {} while(0)
#define OCAML_USDT_HEAP_STATS(domain_id, minor_words, major_words, live_words) do {} while(0)

#define OCAML_USDT_COUNTER_MINOR_PROMOTED(domain_id, bytes) do {} while(0)
#define OCAML_USDT_COUNTER_MINOR_PROMOTED_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MINOR_ALLOCATED(domain_id, bytes) do {} while(0)
#define OCAML_USDT_COUNTER_MINOR_ALLOCATED_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_FORCE_MINOR_ALLOC_SMALL(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_FORCE_MINOR_MAKE_VECT(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_FORCE_MINOR_SET_MINOR_HEAP_SIZE(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_FORCE_MINOR_MEMPROF(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_LIVE_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_LARGE_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_FRAG_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_POOL_LIVE_BLOCKS(domain_id, blocks) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_LARGE_BLOCKS(domain_id, blocks) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_HEAP_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_ALLOCATED_WORDS(domain_id, words) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_ALLOCATED_WORK(domain_id, work) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_DEPENDENT_WORK(domain_id, work) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_EXTRA_WORK(domain_id, work) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_WORK_COUNTER(domain_id, counter) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_ALLOC_COUNTER(domain_id, counter) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_SLICE_TARGET(domain_id, target) do {} while(0)
#define OCAML_USDT_COUNTER_MAJOR_SLICE_BUDGET(domain_id, budget) do {} while(0)
#define OCAML_USDT_COUNTER_REQUEST_MAJOR_ALLOC_SHR(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_REQUEST_MAJOR_ADJUST_GC_SPEED(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_REF_TABLE(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE(domain_id) do {} while(0)
#define OCAML_USDT_COUNTER_REQUEST_MINOR_REALLOC_CUSTOM_TABLE(domain_id) do {} while(0)

#define OCAML_USDT_GC_MINOR_BEGIN_ENABLED() 0
#define OCAML_USDT_GC_MAJOR_BEGIN_ENABLED() 0
#define OCAML_USDT_ALLOC_MINOR_ENABLED() 0
#define OCAML_USDT_HEAP_STATS_ENABLED() 0

#endif /* CAML_WITH_USDT */

#endif /* CAML_USDT_PROBES_H */
